### ISSUE TITLE
Webuahtn Register and Login Problem

### ISSUE THREAD

**Issue by niyazialpay** [Laragear/webpass#16]
### Browser & OS

Brave, Firefox, Chrome

### Have you done this?

- [X] I have checked my logs and I am sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

-

### Description

I did everything exactly as you described in the installation steps. In Laravel 10 I installed version 1.x of your Webauthn package without any problem, but in Laravel 11 I could not complete this installation with the Webauthn 2.x package and Webpass.

When I first did it, everything was working fine, but now I have seen that it only works with Windows Hello face recognition without any changes. I have tried with Yubikey, IOS Face ID, Bitwarden Passkey. It saves them all in the database but cannot access any saved data during the login process. It does not create any data in Yubikey, it does not create a record on Bitwarden Passkey. I have tried all of these in different browsers.

The javascript codes for the registration and login processes I use are as follows

For registration
const attest = async () => await Webpass.attest("{{route('webauthn.register.options')}}", "{{route('webauthn.register')}}");

For login
const assert = async () => await Webpass.assert("{{route('webauthn.login.options')}}", "{{route('webauthn.login')}}");

### Reproduction

```javascript
-
```

**Comment by DarkGhostHunter** [comment]
Stack traces? Responses from the server? Debug messages? Logs?

**Comment by niyazialpay** [comment]
Sorry for the delay. In fact, there is no error message. Everything seems to be working very correctly. For example, the screenshot below was taken while Windows Hello was registering facial recognition, you can see the incoming and outgoing queries in the screenshot.

![image](https://github.com/Laragear/webpass/assets/8478032/3a8826f5-78ff-490c-a7ff-f8d60ab80e00)
![image](https://github.com/Laragear/webpass/assets/8478032/ce2b641a-8695-466b-8d66-f707e84eaf64)

Everything works on Windows Hello
![image](https://github.com/Laragear/webpass/assets/8478032/5312428f-8569-45ca-81d5-e4a7f3949aa7)

![image](https://github.com/Laragear/webpass/assets/8478032/e7cf78b2-c7f7-4e69-b532-116c7993ef55)
![image](https://github.com/Laragear/webpass/assets/8478032/be886dc4-9ccb-412d-b590-e9924dac697a)


This screenshot was also taken while registering the Bitwarden Passkey, as you can see there are no problems during the registration.

![image](https://github.com/Laragear/webpass/assets/8478032/2fb164c8-b994-43a4-b0fc-87fa131d1d0b)
![image](https://github.com/Laragear/webpass/assets/8478032/c846f7df-5399-4794-a01e-45df0b6feedd)

But during the login process the passkey does not come, because the passkey is not saved in the bitwarden environment, I tried the same with Yubikey.

![image](https://github.com/Laragear/webpass/assets/8478032/582813de-5f82-44c7-aa8f-253b832792f9)

I can use Bitwarden passkey and Yubikey to log in to different sites, so I don't think there should be a problem with them.

Unfortunately, there is no error log that I can provide on the server side, because it creates a record to the database without any problems every time it registers.

**Comment by DarkGhostHunter** [comment]
Assertion failures are logged if the app has debug turned on.

**Comment by DarkGhostHunter** [comment]
This may be fixed on Laragear/WebAuthn version 3.0, as it normalizes the userHandle when it's an UUID.

**Comment by emiliopedrollo** [comment]
I'm having the same issue with Yubikey on Laragear/WebAuthn v3.1.0. It works with chrome built-in credentials but fails with Yubikey as it does not save the private key on the device. In both cases the database is populated. 

I only found it curious that the column `aaguid` on the webauthn_credentials table is always `00000000-0000-0000-0000-000000000000` with yubikey, however I don't know if it's somehow related.

**Comment by DarkGhostHunter** [comment]
I belive it's related to https://github.com/Laragear/WebAuthn/issues/96

**Comment by emiliopedrollo** [comment]
> I belive it's related to [Laragear/WebAuthn#96](https://github.com/Laragear/WebAuthn/issues/96)

I'm not sure, as for me it generates a valid uuid (a full zero uuid is valid) and does not have any issues saving in the database. Anyway I just mentioned that because that's just something that I noticed looking in the database, it's probably not even related to the issue which is that the private key is not being saved on my yubikey.

**Comment by DarkGhostHunter** [comment]
> > I belive it's related to [Laragear/WebAuthn#96](https://github.com/Laragear/WebAuthn/issues/96)
> 
> I'm not sure, as for me it generates a valid uuid (a full zero uuid is valid) and does not have any issues saving in the database. Anyway I just mentioned that because that's just something that I noticed looking in the database, it's probably not even related to the issue which is that the private key is not being saved on my yubikey.

Hard to debug without the log stack and comparing with webauthn.io or other test sites. Theoretically, it should work anywhere.

**Comment by emiliopedrollo** [comment]
Digging i little deeper I found that I needed to setup for a `resident key` by enabling `userless` attestation options in order for it to save the private key into the yubikey passkeys. It was just lack of knowledge of my part.

**Comment by DarkGhostHunter** [comment]
I believe you mean the user id.

Not all Authenticators support saving the user ID, but recent do I believe.
