### ISSUE TITLE
[1.2] Cannot import `@laragear/webpass`

### ISSUE THREAD

**Issue by pistvan** [Laragear/webpass#9]
### PHP & Platform

node v20.11.1, npm 10.2.4

### Laravel version

no Laravel

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

I would like to import the library to my Webpack project, but it does not compile.

### Description

Steps of reproduce:

* `npm init -y`
* `npm i typescript ts-loader webpack webpack-cli @laragear/webpass`
* `npx tsc --init`

Create `webpack.config.js` with the following content:
```js
const path = require('path');

module.exports = {
  mode: 'development',
  entry: './src/index.ts',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
  },
};
 ```

Create `src/index.ts`:
```ts
import Webpass from '@laragear/webpass';
console.log(Webpass);
```

### Reproduction

```php
$ npx webpack
```

### Stack trace & logs

```shell
asset main.js 5.9 KiB [compared for emit] (name: main)
runtime modules 937 bytes 4 modules
cacheable modules 10 KiB
  ./src/index.ts 313 bytes [built] [code generated]
  ./node_modules/@laragear/webpass/src/index.ts 57 bytes [built] [code generated]
  ./node_modules/@laragear/webpass/src/webpass.ts 9.68 KiB [built] [code generated]

ERROR in ./node_modules/@laragear/webpass/src/webpass.ts 1:12
Module parse failed: Unexpected token (1:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> import type {
|     AssertionResult,
|     AttestationResult,
 @ ./node_modules/@laragear/webpass/src/index.ts 1:0-31 3:15-22
 @ ./src/index.ts 6:34-62

webpack 5.90.3 compiled with 1 error in 1252 ms
```

**Comment by DarkGhostHunter** [comment]
It's my idea, or Webpack can't compile an imported type? If that the case, checkout Webpack configuration, or the TS version. 

Other than that, I cannot help you. Kinda lost on the bundler universe.

**Comment by Thotsuya** [comment]
I fixed it by removing `exclude: /node_modules/,` , I don't know if it is a valid solution...
